### ISSUE TITLE
Alignment check incomplete

### ISSUE THREAD

**Issue by tommythorn** [djanderson/riscv-5stage-simulator#1]
This doesn't check alignment in all cases:
https://github.com/djanderson/riscv-5stage-simulator/blob/5cdd3fcb9298ce7c2cce882ec289fd08896a9c60/src/memory/data.rs#L29

Fx. if the offset is 1 and the size 2, this is an unaligned access, but 1+2 < 4 and doesn't trigger.
The standard way to check alignment is `(addr & (size - 1)) != 0`.

**Comment by djanderson** [comment]
@tommythorn great catch. I had to whiteboard that one but it makes total sense. Thanks!
